ALTER TABLE shop_products ADD COLUMN stock_quantity integer;
--> statement-breakpoint
ALTER TABLE shop_products ADD COLUMN illustrative integer NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE shop_products ADD COLUMN image_col integer;
--> statement-breakpoint
ALTER TABLE shop_products ADD COLUMN image_row integer;
--> statement-breakpoint
ALTER TABLE shop_products ADD COLUMN image_cols integer;
--> statement-breakpoint
ALTER TABLE shop_products ADD COLUMN image_rows integer;
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000001', 'Manta canelada terracota', 'mantinhas', 'Uma referência de manta com textura canelada e tom terracota.', 'Para acomodar no sofá, na caminha ou na caixa de transporte.', 'Meça o espaço que deseja cobrir e confirme o tecido e a espessura disponíveis.', 'Siga a etiqueta de lavagem e deixe secar completamente antes de usar.', '/assets/mantinhas.webp', NULL, '1', NULL, '1', '0', '0', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000002', 'Manta sherpa creme', 'mantinhas', 'Uma proposta de manta em tom creme, com visual macio de sherpa.', 'Um complemento de aconchego para o local de descanso de cães e gatos.', 'Confirme a composição, as medidas e a espessura da peça com a equipe.', 'Lave conforme a etiqueta e retire pelos com uma escova adequada ao tecido.', '/assets/mantinhas.webp', NULL, '1', NULL, '1', '1', '0', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000003', 'Manta matelassê caramelo', 'mantinhas', 'Uma manta em tom caramelo, com acabamento visual matelassê.', 'Para forrar a caminha ou proteger o lugar preferido do pet.', 'Compare as medidas da manta com as da cama e pergunte pelo acabamento disponível.', 'Confira as instruções de lavagem; evite guardar a peça úmida.', '/assets/mantinhas.webp', NULL, '1', NULL, '1', '0', '1', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000004', 'Manta xadrez aconchego', 'mantinhas', 'Uma proposta de manta xadrez em cores quentes para o cantinho deles.', 'Para usar como forro ou complemento da cama de cães e gatos.', 'Escolha a medida a partir do local de uso e confirme estampas e tecidos em estoque.', 'Respeite a etiqueta e confira o estado do tecido após cada lavagem.', '/assets/mantinhas.webp', NULL, '1', NULL, '1', '1', '1', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000005', 'Suéter de tricô vinho', 'roupinhas', 'Uma referência de suéter com textura de tricô em tom vinho.', 'Uma opção de roupa para os dias mais frescos, conforme a adaptação do pet.', 'Informe comprimento das costas, pescoço e tórax; confirme o tamanho sem apertar.', 'Não force o uso se houver desconforto. Siga as orientações de lavagem da peça.', '/assets/roupinhas.webp', NULL, '1', NULL, '1', '0', '0', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000006', 'Capa de chuva caramelo', 'roupinhas', 'Uma referência de capa de chuva em tom caramelo para passeios.', 'Para consultar opções de proteção durante o passeio em dias de chuva.', 'Meça costas, pescoço e tórax e confirme cobertura e impermeabilidade do modelo real.', 'Confira o ajuste, supervisione o uso e deixe secar após o passeio.', '/assets/roupinhas.webp', NULL, '1', NULL, '1', '1', '0', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000007', 'Colete acolchoado creme', 'roupinhas', 'Uma proposta de colete acolchoado em tom creme.', 'Para consultar uma roupa confortável para os dias mais frios.', 'Informe medidas do pet e confira fechamento, forro e liberdade dos movimentos.', 'Retire se o animal demonstrar incômodo e lave de acordo com a etiqueta.', '/assets/roupinhas.webp', NULL, '1', NULL, '1', '0', '1', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000008', 'Bandana terracota', 'roupinhas', 'Uma bandana em tom terracota para um detalhe no visual.', 'Um acessório para ocasiões especiais ou para o dia a dia.', 'Confira a medida do pescoço e o tipo de fechamento antes de escolher.', 'Use sob supervisão, sem apertar, e retire se a peça prender em algum objeto.', '/assets/roupinhas.webp', NULL, '1', NULL, '1', '1', '1', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000009', 'Caminha oval cacau', 'caminhas', 'Uma referência de caminha oval em tom cacau, com bordas acolhedoras.', 'Para pets que gostam de descansar com o corpo apoiado nas laterais.', 'Meça o pet deitado e confirme a área interna útil, o enchimento e a capa.', 'Verifique se a capa é removível e siga as instruções do fabricante para limpar.', '/assets/caminhas.webp', NULL, '1', NULL, '1', '0', '0', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000010', 'Ninho de pelúcia creme', 'caminhas', 'Uma proposta de caminha em formato de ninho, com visual de pelúcia creme.', 'Para cães e gatos que preferem descansar encolhidos.', 'Confira o diâmetro interno e escolha espaço suficiente para o pet mudar de posição.', 'Retire pelos regularmente e confirme como lavar e secar o enchimento.', '/assets/caminhas.webp', NULL, '1', NULL, '1', '1', '0', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000011', 'Sofá pet terracota', 'caminhas', 'Uma referência de sofá pet com bordas e acabamento em tom terracota.', 'Para criar um lugar próprio de descanso perto da família.', 'Compare comprimento e largura internos com o pet esticado; confirme material e suporte.', 'Consulte a lavagem da capa e mantenha o enchimento totalmente seco.', '/assets/caminhas.webp', NULL, '1', NULL, '1', '0', '1', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000012', 'Cama baixa de madeira', 'caminhas', 'Uma proposta de cama baixa em madeira com almofada.', 'Para organizar um cantinho de descanso de cães ou gatos.', 'Confira dimensões, altura de acesso, estabilidade e capacidade de peso do modelo real.', 'Limpe a estrutura conforme orientação do fabricante e lave a almofada separadamente.', '/assets/caminhas.webp', NULL, '1', NULL, '1', '1', '1', '2', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000013', 'Copo limpa-patas', 'caes', 'Uma referência de copo limpa-patas para a rotina após o passeio.', 'Para consultar opções de limpeza das patinhas antes de entrar em casa.', 'Informe o porte do cão e compare o diâmetro do copo com a largura das patas.', 'Use de acordo com o fabricante, lave o acessório e seque as patas após o uso.', '/assets/acessorios-caes.webp', NULL, '1', NULL, '1', '0', '0', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000014', 'Shampoo suave', 'caes', 'Uma referência de shampoo para a higiene da pelagem canina.', 'Para consultar o produto adequado à rotina de banho do seu cão.', 'Confirme indicação para a espécie, idade, tipo de pelagem e instruções do rótulo.', 'Siga diluição e uso do fabricante; não aplique nos olhos ou ouvidos.', '/assets/acessorios-caes.webp', NULL, '1', NULL, '1', '1', '0', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000015', 'Corda para brincar', 'caes', 'Uma proposta de brinquedo de corda para cães.', 'Para momentos de interação e brincadeira com o tutor.', 'Escolha tamanho proporcional à boca do cão e confirme material e resistência.', 'Supervisione a brincadeira e substitua o brinquedo se soltar fios ou partes.', '/assets/acessorios-caes.webp', NULL, '1', NULL, '1', '2', '0', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000016', 'Escova massageadora', 'caes', 'Uma referência de escova com superfície massageadora.', 'Para consultar opções de escovação e cuidado da pelagem.', 'Informe tipo e comprimento do pelo; confirme o formato de cerdas adequado ao pet.', 'Use com movimentos leves e limpe as cerdas depois de cada uso.', '/assets/acessorios-caes.webp', NULL, '1', NULL, '1', '0', '1', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000017', 'Bola porta-petiscos', 'caes', 'Uma referência de bola com espaço para petiscos.', 'Para variar a brincadeira e oferecer pequenos desafios durante a rotina.', 'Compare o tamanho com a boca do cão e confirme abertura e tipo de petisco indicado.', 'Supervisione o uso, higienize o brinquedo e substitua se aparecerem danos.', '/assets/acessorios-caes.webp', NULL, '1', NULL, '1', '1', '1', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000018', 'Creme para pelagem', 'gatos', 'Uma referência visual de creme para o cuidado da pelagem felina.', 'Para consultar opções específicas para gatos disponíveis na loja.', 'Confirme no rótulo a indicação para gatos, modo de uso e composição do produto real.', 'Não use produtos destinados apenas a cães. Siga o rótulo e a orientação profissional.', '/assets/acessorios-gatos.webp', NULL, '1', NULL, '1', '0', '0', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000019', 'Varinha de penas', 'gatos', 'Uma proposta de varinha com penas para brincar com gatos.', 'Para interação com o tutor, com movimentos que convidam o gato a perseguir.', 'Confira o comprimento da varinha e se penas, fios e partes estão bem fixados.', 'Guarde após a brincadeira e supervisione para evitar ingestão de fios ou partes.', '/assets/acessorios-gatos.webp', NULL, '1', NULL, '1', '1', '0', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000020', 'Comedouro de cerâmica', 'gatos', 'Uma referência de comedouro em cerâmica para gatos.', 'Para organizar o local de alimentação ou água.', 'Confira diâmetro, profundidade, capacidade e acabamento da peça disponível.', 'Lave regularmente, enxágue bem e substitua caso a cerâmica lasque ou rache.', '/assets/acessorios-gatos.webp', NULL, '1', NULL, '1', '2', '0', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000021', 'Túnel para brincar', 'gatos', 'Uma proposta de túnel para esconder, explorar e brincar.', 'Para variar o espaço de brincadeiras e descoberta dos gatos.', 'Compare diâmetro e comprimento com o porte do gato e o espaço disponível em casa.', 'Confira se a estrutura está íntegra e limpe conforme as instruções do modelo.', '/assets/acessorios-gatos.webp', NULL, '1', NULL, '1', '0', '1', '3', '2');
--> statement-breakpoint
INSERT OR IGNORE INTO shop_products (id, name, category, description, usage, selection, care, image, price, available, stock_quantity, illustrative, image_col, image_row, image_cols, image_rows) VALUES ('00000000-0000-4000-8000-000000000022', 'Brinquedo com catnip', 'gatos', 'Uma referência de brinquedo com proposta de catnip para gatos.', 'Para consultar opções de brincadeira; o interesse por catnip varia entre os gatos.', 'Confirme se a peça contém catnip, o material externo e o tamanho do brinquedo real.', 'Use sob supervisão e retire o brinquedo se a costura abrir ou o recheio ficar exposto.', '/assets/acessorios-gatos.webp', NULL, '1', NULL, '1', '1', '1', '3', '2');
