import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const memory=new Map();
const context=vm.createContext({window:{},location:{origin:'https://duduwwl.github.io'},document:{querySelector:()=>null},localStorage:{getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value)},URL,Intl,Date,structuredClone,crypto:{randomUUID}});
vm.runInContext(readFileSync('public/demo-admin-data.js','utf8'),context);
const api=context.window.LOVE_PETS_DEMO_API;
const request=(path,method,body)=>api(path,{method,body:JSON.stringify(body)});
let state=await api('/api/admin/state');
assert.equal(state.appointments.length,3);
assert(state.appointments.every(a=>a.guardian_name.startsWith('Cliente exemplo')&&!a.phone));
const first=state.appointments[0];
await assert.rejects(()=>request('/api/admin/blocks','POST',{date:first.date,time:first.time}),/reserva/);
await request('/api/admin/appointments/'+first.id,'PATCH',{status:'cancelled'});
await request('/api/admin/blocks','POST',{date:first.date,time:first.time,reason:'Teste'});
await assert.rejects(()=>request('/api/admin/appointments/'+first.id,'PATCH',{status:'confirmed'}),/bloqueado/);
state=await api('/api/admin/state');
assert.equal(state.blocks.length,1);
await api('/api/admin/blocks/'+state.blocks[0].id,{method:'DELETE'});
await request('/api/admin/appointments/'+first.id,'PATCH',{status:'confirmed'});
const services=state.services.map(s=>({...s,durationMinutes:30}));
await request('/api/admin/services','PUT',{services});
await assert.rejects(()=>request('/api/admin/services','PUT',{services:services.map(s=>({...s,durationMinutes:17}))}),/duração/);
await assert.rejects(()=>api('/api/calendar.ics'),/indisponível/);
const calendar=await api('/api/admin/calendar-url');
assert(calendar.calendarText.includes('BEGIN:VCALENDAR'));
assert(calendar.calendarText.includes('DEMONSTRAÇÃO'));
assert(!calendar.url);
assert(memory.size===1);
const filtered=await api('/api/admin/state?from=2000-01-01&to=2000-01-02');
assert.equal(filtered.appointments.length,0);
console.log('Demo verified: fictional contacts, local updates, conflict handling, blocks and sample calendar; no live API access.');
