import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const memory=new Map();
const context=vm.createContext({window:{LOVE_PETS_DEMO_MODE:true},location:{origin:'https://duduwwl.github.io'},document:{querySelector:()=>null},localStorage:{getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value)},URL,Intl,Date,structuredClone,crypto:{randomUUID}});
vm.runInContext(readFileSync('public/demo-admin-data.js','utf8'),context);
const api=context.window.LOVE_PETS_DEMO_API;
const request=(path,method,body)=>api(path,{method,body:JSON.stringify(body)});
let state=await api('/api/admin/state');
assert.equal(state.appointments.length,3);
assert(state.appointments.every(a=>a.guardian_name.startsWith('Cliente exemplo')&&!a.phone));
const bookingDate=state.appointments[0].date;
const openSlots=await api(`/api/availability?date=${bookingDate}&service=banho`);
assert(openSlots.slots.length>0);
const requestedTime=openSlots.slots[0];
const created=await request('/api/appointments','POST',{date:bookingDate,time:requestedTime,service:'banho',petName:'Nina',petType:'cao',guardianName:'Cliente teste',phone:'35999998888'});
assert.match(created.id,/^demo-/);
assert(!(await api(`/api/availability?date=${bookingDate}&service=banho`)).slots.includes(requestedTime));
state=await api('/api/admin/state');
assert(state.appointments.some(a=>a.id===created.id&&a.pet_name==='Nina'));
const fullDate=new Date(`${state.today}T12:00:00Z`);fullDate.setUTCDate(fullDate.getUTCDate()+4);
const fullDateValue=fullDate.toISOString().slice(0,10),fullWeekday=fullDate.getUTCDay();
const shortHours=state.hours.map(day=>day.weekday===fullWeekday?{...day,enabled:true,openTime:'12:00',closeTime:'13:00'}:day);
await request('/api/admin/hours','PUT',{hours:shortHours});
const fullBooking=await request('/api/appointments','POST',{date:fullDateValue,time:'12:00',service:'banho',petName:'Pipoca',petType:'gato',guardianName:'Cliente teste 2',phone:'35999997777'});
assert.match(fullBooking.id,/^demo-/);
assert.equal((await api(`/api/availability?date=${fullDateValue}&service=banho`)).slots.length,0);
await request('/api/admin/hours','PUT',{hours:state.hours});
const first=state.appointments[0];
await assert.rejects(()=>request('/api/admin/blocks','POST',{date:first.date,time:first.time}),/reserva/);
await request('/api/admin/appointments/'+first.id,'PATCH',{status:'cancelled'});
await request('/api/admin/blocks','POST',{date:first.date,time:first.time,reason:'Teste'});
await assert.rejects(()=>request('/api/admin/appointments/'+first.id,'PATCH',{status:'confirmed'}),/bloqueado/);
state=await api('/api/admin/state');
assert.equal(state.blocks.length,1);
await api('/api/admin/blocks/'+state.blocks[0].id,{method:'DELETE'});
await request('/api/admin/appointments/'+first.id,'PATCH',{status:'confirmed'});
const services=state.services.map(s=>({...s,durationMinutes:30}));
await request('/api/admin/services','PUT',{services});
await assert.rejects(()=>request('/api/admin/services','PUT',{services:services.map(s=>({...s,durationMinutes:17}))}),/duração/);
await assert.rejects(()=>api('/api/calendar.ics'),/indisponível/);
const calendar=await api('/api/admin/calendar-url');
assert(calendar.calendarText.includes('BEGIN:VCALENDAR'));
assert(calendar.calendarText.includes('DEMONSTRAÇÃO'));
assert(!calendar.url);
assert(memory.size===1);
const filtered=await api('/api/admin/state?from=2000-01-01&to=2000-01-02');
assert.equal(filtered.appointments.length,0);
console.log('Demo verified: fictional contacts, local updates, conflict handling, blocks and sample calendar; no live API access.');
